language: rust
sudo: required
cache:
  cargo: true
  directories:
  - "${HOME}/kcov-build/usr/local/bin/kcov"
rust:
#  - stable
#  - beta
  - nightly

script: make ci

env:
  global:
  - RUSTFLAGS="-C link-dead-code"

matrix:
  allow_failures:
    - rust: nightly
  fast_finish: true

before_install:
  - sudo apt-get update

# Required by codecov
addons:
  apt:
    packages:
      - libcurl4-openssl-dev
      - libelf-dev
      - libdw-dev
      - cmake
      - gcc
      - binutils-dev
      - libiberty-dev
      - jq

jobs:
  include:
    - stage: coverage
      rust: nightly
      script:
        - ./scripts/code_coverage.sh

notifications:
  email:
    on_success: never
