sudo: false
addons:
  apt:
    packages:
      - libcurl4-openssl-dev
      - libelf-dev
      - libdw-dev
      - cmake
      - gcc
      - binutils-dev
      - libiberty-dev
      - jq

language: rust

cache:
  directories:
  - "${HOME}/kcov/"

env:
- PATH=$PATH:${HOME}/kcov/bin

#before_install:
#- if [ ! -d "${HOME}/kcov/bin" ]; then wget https://github.com/SimonKagstrom/kcov/archive/master.tar.gz;
#  tar xzf master.tar.gz;
#  cd kcov-master;
#  mkdir build;
#  cd build;
#  cmake -DCMAKE_INSTALL_PREFIX=${HOME}/kcov ..;
#  make;
#  make install;
#  cd ../..;
#  rm -rf kcov-master;
#  mkdir -p coverage; fi

script: make ci

jobs:
  include:
    - stage: coverage
      rust: nightly
      script:
        - ./scripts/code_coverage.sh

#language: rust
#sudo: required
#cache:
#  cargo: true
#  directories:
#  - "${HOME}/kcov-build/usr/local/bin/kcov"
#rust:
##  - stable
##  - beta
#  - nightly
#
#script: make ci
#
#env:
#  global:
#  - RUSTFLAGS="-C link-dead-code"
#
#matrix:
#  allow_failures:
#    - rust: nightly
#  fast_finish: true
#
#before_install:
#  - sudo apt-get update
#
## Required by codecov
#addons:
#  apt:
#    packages:
#      - libcurl4-openssl-dev
#      - libelf-dev
#      - libdw-dev
#      - cmake
#      - gcc
#      - binutils-dev
#      - libiberty-dev
#      - jq
#
#jobs:
#  include:
#    - stage: coverage
#      rust: nightly
#      script:
#        - ./scripts/code_coverage.sh
#
#notifications:
#  email:
#    on_success: never
